sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fi9MBdnqAaBiJ9EpAzbqgfVaZjDz44xjNuHYKXaRzb/r6HzrJK1jA6xmjTTo5eCTDTaIaAA0/DCWrd3hH6b9Seo1AG2FSkS1wa8B5lEPczLXJdfGZFenYUma5vJicLwGlUB+Bok1o9qQjrbGXIhpiRj9ea/3MAEkgdMLrWptqWRR4baqh/gjQp7GKc0FT+udETGoYJ5gQefcKnwjqcNuX/IRg6glo38PEUGkKWJbhD74p9VMmf0jVRV2VvoDRBJyh1Uq9d479aRYdgReMyn0k8fdz8KQvvGDoE7XQR3cr7PPm3CZyvRszfUYz5fY/fMmjkgVYDjKDJp51FJ10H/n+VSgkF+0QwtjGN0Q1hGdfmYBYx4JK4Yf1FWfo1Wg/b1+5CLce09uQwYz82kKk7aFQakVWDbuoOZqkt2tqi7JSNnShqFLQiehJYzbyu11cotOIOeHP+zLoiYqrLv1xpgMuSsWM1aZmoxAjo1pDGplUaGL3h+Oiga0Q9dsh1+rmkxtLURmU4lHc8h5/bOmzQiYO3uJ4Jv/9BjPaLD349J2PHlMGaUVupUr2+LY2QFRREAJ9ovKcylNZmzKdvjpl4h2HY0aieokZkRVsDxOaw32HtGffMMRyKhcG/wvtG6QdrBOukwhbCV2n35gN2hsDggEj6TDx3jpqumxTXNOlTSjUdg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Introduction-to-the-Compleat-Angler_2422
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy